version: "3.0"
services:
  restserver:
    container_name: chemvesol-modbusclient
    build: python
    command: python3 app.py
    volumes:
      - type: bind
        source: ./log
        target: /var/log
      - type: bind
        source: ./spool
        target: /var/modBusSpool

volumes:
  log:
  spool:
